### ISSUE TITLE
Signing fails on latest Metamask update

### ISSUE THREAD

**Issue by steddyman** [ethereum-attestation-service/eas-sdk#42] opened 2023-06-29 15:27 UTC
Anyone else seeing this?

https://github.com/MetaMask/metamask-extension/issues/19826

Happens for me on all chains now, either in my own frontend or using the easscan.org site when creating new attestations.

**Comment by slavik0329** [comment] 2023-06-29 19:22
I am unable to reproduce this issue. Can you provide more details about your set up?

**Comment by steddyman** [comment] 2023-06-29 21:05
> @steddyman I am unable to reproduce this issue. Can you provide more details about your set up?

Sure.  I am just using the easscan.org site against the Sepolia testnet.  If you view the Metamask issue, the team have now confirmed they are seeing this issue also.

I am also getting from my own APP using the contract deployed to Sepolia.

**Comment by slavik0329** [comment] 2023-08-17 19:39
closing this as we have been unable to replicate

**Closed** 2023-08-17 19:39 UTC
